services:
  app:
    build: .
    container_name: handmade-api
    restart: always

    ports:
      - '3000:3000'
      - '51212:51212'

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - ./.docker.env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16

    container_name: handmade-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: handmade_marketplace

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: handmade-redis

    restart: always

    ports:
      - '6379:6379'

volumes:
  postgres_data:
